version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
      
  worker:
    build: 
        context: ./
        network: host
    command: celery -A main worker -l info -E
    user: nobody
    volumes:
      - ./:/code
    environment:
      PYTHONPATH: /code
    depends_on:
      - redis

  beat:
    build: 
        context: ./
        network: host
    command: celery -A main beat
    user: nobody
    volumes:
      - ./:/code
    environment:
      PYTHONPATH: /code
    depends_on:
      - redis
      
  flower:
    build: 
        context: ./
        network: host
    volumes:
      - ./:/code
    environment:
      PYTHONPATH: /code      
    command: celery -A main flower
    ports:
      - 5555:5555
    depends_on:
      - worker
      - redis
      
